name: Deploy to Cloud Run

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: us-central1                 # <- corrige aqui
  REPOSITORY: app-registry            # <- crie esse repositório no Artifact Registry
  SERVICE_NAME: meucrud-api           # <- nome do serviço no Cloud Run

jobs:
  deploy:
    runs-on: ubuntu-latest

    # aqui SIM podemos referenciar env.*
    env:
      IMAGE_NAME: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE_NAME }}:${{ github.sha }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }} # JSON da SA com permissão em AR e Cloud Run
          export_default_credentials: true

      - name: Configure Docker auth for Artifact Registry
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Build image
        run: |
          docker build -t $IMAGE_NAME .

      - name: Push image
        run: |
          docker push $IMAGE_NAME

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image $IMAGE_NAME \
            --region ${{ env.REGION }} \
            --platform managed \
            --allow-unauthenticated
